sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t as/dockrct -f Dockerfile.dev .

script:
  - docker run -e CI=true as/dockrct npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Drct"
  environment: "Drct-env"
  bucket_name: "elasticbeanstalk-us-east-2-876301936298"
  bucket_path: "Drct"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
